### PR TITLE
upgrade ScalaTest and spire; drop 2.11 support

### PR DESCRIPTION
**Pull request by SethTisue**
in order to keep libra in the Scala 2.13 community build (which is desirable, but certainly not essential), it would be helpful to have this merged

context is scala/community-build#1172

### CODE REVIEW

**Comment by SethTisue** [comment]
I see this repo has a .travis.yml, but it doesn't appear that Travis-CI is actually enabled here?

**Comment by SethTisue** [comment]
I see the newer Spire version is only available for 2.12 and 2.13. I'll add another commit dropping 2.11 support.

**Comment by SethTisue** [comment]
ping @zainab-ali ?

**Comment by zainab-ali** [comment]
Thank you very much @SethTisue !  Many, many apologies for being so late on this.

I've moved the repo over to GitHub Actions.  Would you mind editing the `github/workflows/main.yml` and `github/worflows/feature.yml` files instead?

**Comment by SethTisue** [comment]
awesome! community build followup at https://github.com/scala/community-build/pull/1248

**Pull request merged**
