### PR TITLE
Add angular velocity units

### PR DESCRIPTION
**Pull request by ldrygala**
Add angular velocity units, as referenced in #38

### CODE REVIEW

**Comment by ldrygala** [comment]
Hi @zainab-ali, as you see i created pull request but unfortunately it failed on travis-ci (locally it compiles and https://travis-ci.org/ldrygala/libra/jobs/303949407 it also compiles). It is strange for me that it treat libra.Unit as scala Unit. Did you have similar problem ? I try to fix it but currently i don't have any idea how, so maybe you could give me some hint

**Comment by zainab-ali** [comment]
Thanks for the PR @ldrygala !
I recently pushed a change renaming `Unit` to `UnitOfMeasure`.  This can be fixed by pulling from the master branch and renaming `Unit` in the new files to `UnitOfMeasure`.

Once this is merged in can I add you to the contributors list?

**Comment by ldrygala** [comment]
thank you for hint :) what a silly mistake

**Comment by zainab-ali** [comment]
Looks great :+1:

**Comment by ldrygala** [comment]
one more time thank you @zainab-ali for helping me with my first PR. i thought that maybe i could add radians in next PR ?

**Comment by zainab-ali** [comment]
That would be great!  I think that radians can go in the same `nonsi` package as degrees for now.  I'm probably going to do a refactor in #48 over the next few weeks which will change that.

**Pull request merged**
